name: Continuous Integration
on:
  push:
    paths:
      - '**'
      - '.github/**/*.yml'
    branches:
      - main
  pull_request:
jobs:
  test:
    name: "Tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install poetry
        uses: Gr1N/setup-poetry@v8
      - name: Install Dependencies using Poetry
        run: poetry install --no-root
      - name: Run Tests w. coverage, Unity and Integration
        run:  make test