name: deploy to Azure
on:
  release:
    types:
      - created
    branches:
      - master

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout with all tags
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10.6'

      - name: Install poetry
        uses: Gr1N/setup-poetry@v9
        with:
          poetry-version: '1.2.2'

      - name: Update version
        env:
          VERSION: ${{ github.event.release.tag_name }}
        run: |
          poetry version $VERSION
          

      - name: 'azure Docker Login'
        uses: azure/docker-login@v2
        with:
          login-server: ${{ secrets.AZURE_REGISTRY_SERVER }}
          username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
          password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}

      - name: 'push to azure'
        env:
          ECR_REPOSITORY: ${{ secrets.AZURE_REGISTRY_SERVER }}/event-processing-pipeline
          IMAGE_TAG: ${{ github.event.release.tag_name }}
        run: |
          docker build -t $ECR_REPOSITORY:$IMAGE_TAG . 
          docker push $ECR_REPOSITORY:$IMAGE_TAG
