name: autopep8
on: pull_request
jobs:
  autopep8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: autopep8
        id: autopep8
        uses: peter-evans/autopep8@17154d022c0533db2436a6873162d87133be13b2
        with:
          token: ${{ secrets.PRIVATE_ACCESS_TOKEN }}
          args: --exit-code --recursive --in-place --aggressive --aggressive .
      - name: Commit autopep8 changes
        if: steps.autopep8.outputs.exit-code == 2
        run: |
          git config --global user.email "milosjava@gmail.com"
          git config --global user.name "milosjava"
          git commit -am "Automated autopep8 changes [bot]"
          git push
